#!/usr/bin/env bash

echo 'Install general dependencies'
sudo apt install \
     i3 \
     ripgrep \
     libssl-dev

echo 'Install dev deps'
sudo apt install \
     git \
     clang \
     clangd \
     make \
     ninja-build \
     python3-pip \
     libxpm-dev \
     libjpeg-dev \
     libgif-dev \
     libtiff-dev \
     libgnutls28-dev \
     libgtk-3-dev \
     openjdk-11-jdk

echo 'Install nodejs'
echo '============================================'
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
sudo apt install -y nodejs
