#!/usr/bin/env bash

echo Updates brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

echo Install essentials
brew install --cask emacs
brew install wget
brew install git
brew install tmux
brew install mosh
brew install ripgrep
brew install ctags
brew install node

brew cleanup -s
