#!/usr/bin/env bash

echo "Install and update brew"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew update
brew upgrade


echo "Install essentials"

brew install wget \
    git \
    tmux \
    mosh \
    ripgrep \
    ctags \
    node \
    fd \
    glslang \
    isort \
    pipenv \
    tidy

brew cleanup -s
