#!/usr/bin/env bash

platformTmp="$(uname -s)"

case "${platformTmp}" in
    Linux*)   platform=Linux;;
    Darwin*)  platform=macOS;;
    CYGWIN*)  platforme=Cygwin;;
    MINGW*)   platform=MinGw;;
    *)        platform="UNKNOWN:${platformTmp}":
esac

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

echo 'Setup directories'
sh ${PWD}/scripts/setup_directories

echo 'Install dependencies'
if [ "${platform}" == "macOS" ]; then
    echo 'Found macOS...'
    sh ${PWD}/scripts/macos/dependencies
    if [ $? -eq 0 ]; then
        success "dependencies installed"
    else
        fail "error installing dependencies"
    fi
fi

if [ "${platform}" == "Linux" ]; then
    echo 'Found Linux...'
    sh ${PWD}/scripts/linux/dependencies
    if [ $? -eq 0 ]; then
        success "dependencies installed"
    else
        fail "error installing dependencies"
    fi

    echo 'Create Linux Aliases'
    if [ ! -f ${HOME}/.bash_profile ]; then
        ln -vs ${PWD}/.bash_profile ~/.bash_profile
        success "${HOME}/.bash_profile created"
    else
        info "${HOME}/.bash_profile already exists"
    fi
fi

echo 'Create aliases'

if [ ! -f ${HOME}/.editorconfig ]; then
    ln -vs ${PWD}/.editorconfig ~/.editorconfig
    success "${HOME}/.editorconfig created"
else
    info "${HOME}/.editorconfig already exists"
fi

echo 'Clone .emacs.d'

if [ ! -d ${HOME}/.emacs.d ]; then
    git clone https://github.com/tmn/.emacs.d.git ~/.emacs.d
    success "${HOME}/.emacs.d cloned"
else
    info "${HOME}/.emacs.d/ already exists"
fi


echo 'done'
