#!/usr/bin/env bash

echo Updates brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

brew tap d12frosted/emacs-plus

echo Install essentials
brew install wget
brew install fish
brew install git
brew install emacs-plus --without-spacemacs-icon --with-natural-title-bar
brew install tmux
brew install mosh
brew install nodejs

brew cleanup
