#!/usr/bin/env bash

echo 'Install developer tools'
xcode-select --install

echo 'Install brew'
sh ${PWD}/scripts/brew

echo 'Clone emacs config'
if [ ! -d "${HOME}/.emacs.d/" ]; then
    git clone git@github.com:tmn/.emacs.d.git ~/.emacs.d
fi

npm config set prefix '~/.npm-global/'
