#!/usr/bin/env bash

brew install \
ansible \
autoconf \
cmake \
coreutils \
ctags \
dbus \
editorconfig \
fd \
gcc \
git \
glslang \
gnu-sed \
gnupg \
gnutls \
gomodifytags \
gopls \
gotests \
grep \
imagemagick \
isort \
jansson \
ktlint \
libgccjit \
libgit2 \
librsvg \
libxml2 \
markdown \
mosh \
ncurses \
node \
pipenv \
pkg-config \
shellcheck \
texinfo \
tig \
tmux \
tree-sitter \
wget \
yt-dlp \
zsh \
zsh-autosuggestions \
zsh-completions

brew cleanup -s