#!/usr/bin/env bash

if [ ! -d ${HOME}/.config ]; then
    mkdir ${HOME}/.config
fi

if [ ! -d ${HOME}/.npm-global ]; then
    mkdir ${HOME}/.npm-global

    if [ ! -d ${HOME}/.npm-global/bin ]; then
        mkdir ${HOME}/.npm-global/bin
    fi
fi
