## Prompt

source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
setopt PROMPT_SUBST
PROMPT='%F{135}%n%f at %F{166}%m%f in %F{118}%~%f$(__git_ps1 " (%s)")
$ '

########## Aliases ##########

alias l='eza -lbF --git  --sort=type'
alias la='eza -lbhHigUmuSa --sort=type --time-style=long-iso --git --color-scale'
alias ll='eza -lbGF --git  --sort=type'
alias llm='eza -lbGd --git --sort=modified'
alias ls='eza --sort=type'
alias lx='eza -lbhHigUmuSa@ --sort=type  --time-style=long-iso --git --color-scale'


########## Cargo ##########
. "$HOME/.cargo/env"


########## Zsh ##########

if (( ${+commands[brew]} )); then
    # zsh-completion
    fpath=(
        $(brew --prefix)/share/zsh-completions
        $(brew --prefix)/share/zsh/functions
        $(brew --prefix)/share/zsh/site-functions
        $fpath
    )
    
    autoload -Uz compinit
    compinit

    # zsh-autosuggestions
    source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
